### ISSUE TITLE
Thumbnails aren't small... at all

### ISSUE THREAD

**Issue by underr** [phikal/4jhan-server#11]
Using `testing` branch, they're at the same size that original image's.

That's strange, because the code seems right.

**Comment by phikal** [comment]
It's working for me. This was the original image (1), and this was the compressed one (2).
1. ![56215447e5458208488b5f7d4b573cdd](https://cloud.githubusercontent.com/assets/6370419/6867630/3af84714-d484-11e4-9a88-a0ebc95a3cf7.png)
2. ![56215447e5458208488b5f7d4b573cdd](https://cloud.githubusercontent.com/assets/6370419/6867632/3fd0b208-d484-11e4-8597-a28a3ca2b814.png)

Are you sure that 4jhan compressed and wrote the image at all? If it can't find the image in `./thumb/`, it will send you the original.

**Comment by underr** [comment]
It's really weird, there must be something wrong with my setup. I tried on a clean 4jhan and it throws this at me:

```
4jhan server listening on port 3000
Database set up.
{ [Error: ENOENT: no such file or directory, unlink './thumb/a1a2a8eef7a95c48e9047e95b2272a55.jpg']
  errno: -2,
  code: 'ENOENT',
  syscall: 'unlink',
  path: './thumb/a1a2a8eef7a95c48e9047e95b2272a55.jpg' }
```

**Comment by phikal** [comment]
What does your project directory look like?

**Comment by underr** [comment]
It's the default 4jhan, cloned from the testing branch.

**Comment by phikal** [comment]
But do you have a writeable `./thumb/` directory? What image do you get
when you call `GET:/thumb/`? Are you using `config.static = false`?

**Comment by phikal** [comment]
Yeah, I checked, when you clone the project, `./img` and `./thumb/` are not included.

I'm going to implement [this soulution](http://stackoverflow.com/questions/115983/how-can-i-add-an-empty-directory-to-a-git-repository), and then it could work.

**Comment by underr** [comment]
Nice, now it works. I don't know how I didn't noticed the lack of these, though.
