### ISSUE TITLE
Use plain JS for config file

### ISSUE THREAD

**Issue by underr** [phikal/4jhan-server#2]
Why use JSON for it? 

You can't even have comments and have to add "" everywhere.

**Comment by phikal** [comment]
The reason for JSON was just that its easier to read with `require` and that is a well known format. 

I didn't realy think that the `"`'s were a problem, and don't know why you would need comments.

I'd by happy the integrate some simpler config format, if I were given an alternative.

**Comment by underr** [comment]
Right.
Just to be sure, is the sample config missing some keys or you'll add them after implementing everything?

**Comment by phikal** [comment]
In principle all keys are optional, `nsfw` for example defaults to `false` if not specified.
