### ISSUE TITLE
Drop MongoDB for Knex.js

### ISSUE THREAD

**Issue by underr** [phikal/4jhan-server#8]
If MongoDB isn't a deal breaker, you could drop it and manage three different DB systems (Postgres, MySQL and SQLite3) **once** with [Knex.js](http://knexjs.org/). I have used it before and it would fit nicelly with 4jhan.

Because mantaining four (as PostgreSQL support is planned) DB systems doesn't sound nice at all, especially when one of them is noSQL.

**Comment by phikal** [comment]
In general it's not a bad idea, and it has been suggested, but what would be the benefit of `knex,js` over [Sequelize](http://docs.sequelizejs.com/en/latest/), [node-orm2](http://dresende.github.io/node-orm2/) or other orms?

**Comment by underr** [comment]
Oh, that would be a simple matter of taste. I haven't used any of those, just Knex.js, so it's what I know of ORMs.

**Comment by phikal** [comment]
If there were a bug, a more popular orm would be better, since there would be more people which could fix it. And then there is the question of size. I personally am running this on a [raspberry pi](einhorn.ddns.net), and I don't want too much of my limited storage "wasted" on libraries. That was the idea behind the current approach. You don't have to install the other database libraries if you're not using them.

**Comment by underr** [comment]
By size:
- node-orm2: **2,1MB**
- sequelize: **3,1BMB**
- knex: **5,7MB**

node-orm2 wins, but it should be noted that while node-orm2 and sequelize work with noSQL-like schemes, knex is more SQL-like. I don't see any problem with both.

**Comment by phikal** [comment]
And do you know anything about the speed?

**Comment by underr** [comment]
How would I test that? I don't think test units would do it.

Anyway, about popularity:
**node-orm2**: 124 downloads in the last day 
**knex**: 1,627 downloads in the last day
**sequelize**: 1,884 downloads in the last day

**Comment by phikal** [comment]
I'm going to try and implement it with sequelize, it looks like the best option right now. If you realy want to, you could try a knex implementation, it might be better.

**Comment by phikal** [comment]
node-orm2 has been implemented with 1fa56dd34d0fd62d9fc8fe5639c39236b7c7d894.
